# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slu_img_stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14slu_img_stream.proto\x12\x0csluimgstream\"6\n\x1bReadyToReceiveImagesRequest\x12\x17\n\x0freadyClientFlag\x18\x01 \x01(\x08\"4\n\x0eResponseImages\x12\x10\n\x08img_size\x18\x01 \x01(\r\x12\x10\n\x08img_data\x18\x02 \x01(\x0c\":\n\x14ProcessedDataRequest\x12\x10\n\x08img_size\x18\x01 \x01(\r\x12\x10\n\x08img_data\x18\x02 \x01(\x0c\"6\n\x14ResponseDataReceived\x12\x1e\n\x16\x61\x63knowledgeDataReceive\x18\x01 \x01(\x08\x32\xc4\x01\n\x0cSluImgStream\x12Y\n\nSendImages\x12).sluimgstream.ReadyToReceiveImagesRequest\x1a\x1c.sluimgstream.ResponseImages\"\x00\x30\x01\x12Y\n\x0bReceiveData\x12\".sluimgstream.ProcessedDataRequest\x1a\".sluimgstream.ResponseDataReceived\"\x00(\x01\x62\x06proto3')



_READYTORECEIVEIMAGESREQUEST = DESCRIPTOR.message_types_by_name['ReadyToReceiveImagesRequest']
_RESPONSEIMAGES = DESCRIPTOR.message_types_by_name['ResponseImages']
_PROCESSEDDATAREQUEST = DESCRIPTOR.message_types_by_name['ProcessedDataRequest']
_RESPONSEDATARECEIVED = DESCRIPTOR.message_types_by_name['ResponseDataReceived']
ReadyToReceiveImagesRequest = _reflection.GeneratedProtocolMessageType('ReadyToReceiveImagesRequest', (_message.Message,), {
  'DESCRIPTOR' : _READYTORECEIVEIMAGESREQUEST,
  '__module__' : 'slu_img_stream_pb2'
  # @@protoc_insertion_point(class_scope:sluimgstream.ReadyToReceiveImagesRequest)
  })
_sym_db.RegisterMessage(ReadyToReceiveImagesRequest)

ResponseImages = _reflection.GeneratedProtocolMessageType('ResponseImages', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEIMAGES,
  '__module__' : 'slu_img_stream_pb2'
  # @@protoc_insertion_point(class_scope:sluimgstream.ResponseImages)
  })
_sym_db.RegisterMessage(ResponseImages)

ProcessedDataRequest = _reflection.GeneratedProtocolMessageType('ProcessedDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSEDDATAREQUEST,
  '__module__' : 'slu_img_stream_pb2'
  # @@protoc_insertion_point(class_scope:sluimgstream.ProcessedDataRequest)
  })
_sym_db.RegisterMessage(ProcessedDataRequest)

ResponseDataReceived = _reflection.GeneratedProtocolMessageType('ResponseDataReceived', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATARECEIVED,
  '__module__' : 'slu_img_stream_pb2'
  # @@protoc_insertion_point(class_scope:sluimgstream.ResponseDataReceived)
  })
_sym_db.RegisterMessage(ResponseDataReceived)

_SLUIMGSTREAM = DESCRIPTOR.services_by_name['SluImgStream']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _READYTORECEIVEIMAGESREQUEST._serialized_start=38
  _READYTORECEIVEIMAGESREQUEST._serialized_end=92
  _RESPONSEIMAGES._serialized_start=94
  _RESPONSEIMAGES._serialized_end=146
  _PROCESSEDDATAREQUEST._serialized_start=148
  _PROCESSEDDATAREQUEST._serialized_end=206
  _RESPONSEDATARECEIVED._serialized_start=208
  _RESPONSEDATARECEIVED._serialized_end=262
  _SLUIMGSTREAM._serialized_start=265
  _SLUIMGSTREAM._serialized_end=461
# @@protoc_insertion_point(module_scope)
