# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import slu_img_stream_pb2 as slu__img__stream__pb2


class SluImgStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendImages = channel.unary_stream(
                '/sluimgstream.SluImgStream/SendImages',
                request_serializer=slu__img__stream__pb2.ReadyToReceiveImagesRequest.SerializeToString,
                response_deserializer=slu__img__stream__pb2.ResponseImages.FromString,
                )
        self.ReceiveData = channel.stream_unary(
                '/sluimgstream.SluImgStream/ReceiveData',
                request_serializer=slu__img__stream__pb2.ProcessedDataRequest.SerializeToString,
                response_deserializer=slu__img__stream__pb2.ResponseDataReceived.FromString,
                )


class SluImgStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SluImgStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendImages': grpc.unary_stream_rpc_method_handler(
                    servicer.SendImages,
                    request_deserializer=slu__img__stream__pb2.ReadyToReceiveImagesRequest.FromString,
                    response_serializer=slu__img__stream__pb2.ResponseImages.SerializeToString,
            ),
            'ReceiveData': grpc.stream_unary_rpc_method_handler(
                    servicer.ReceiveData,
                    request_deserializer=slu__img__stream__pb2.ProcessedDataRequest.FromString,
                    response_serializer=slu__img__stream__pb2.ResponseDataReceived.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sluimgstream.SluImgStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SluImgStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sluimgstream.SluImgStream/SendImages',
            slu__img__stream__pb2.ReadyToReceiveImagesRequest.SerializeToString,
            slu__img__stream__pb2.ResponseImages.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/sluimgstream.SluImgStream/ReceiveData',
            slu__img__stream__pb2.ProcessedDataRequest.SerializeToString,
            slu__img__stream__pb2.ResponseDataReceived.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
